---
name: Build, test and publish to GH packages

"on":
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: burrunan/gradle-cache-action@v1
        name: test
        with:
          arguments: test